# This file was automatically generated by SWIG (http://www.swig.org).
# Version 1.3.40
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.
# This file is compatible with both classic and new-style classes.

from sys import version_info
if version_info >= (2,6,0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_avl', [dirname(__file__)])
        except ImportError:
            import _avl
            return _avl
        if fp is not None:
            try:
                _mod = imp.load_module('_avl', fp, pathname, description)
            finally:
                fp.close()
            return _mod
    _avl = swig_import_helper()
    del swig_import_helper
else:
    import _avl
del version_info
try:
    _swig_property = property
except NameError:
    pass # Python < 2.2 doesn't have 'property'.
def _swig_setattr_nondynamic(self,class_type,name,value,static=1):
    if (name == "thisown"): return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name,None)
    if method: return method(self,value)
    if (not static) or hasattr(self,name):
        self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)

def _swig_setattr(self,class_type,name,value):
    return _swig_setattr_nondynamic(self,class_type,name,value,0)

def _swig_getattr(self,class_type,name):
    if (name == "thisown"): return self.this.own()
    method = class_type.__swig_getmethods__.get(name,None)
    if method: return method(self)
    raise AttributeError(name)

def _swig_repr(self):
    try: strthis = "proxy of " + self.this.__repr__()
    except: strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except AttributeError:
    class _object : pass
    _newclass = 0



def inserts(*args):
  return _avl.inserts(*args)
inserts = _avl.inserts

def find_pos(*args):
  return _avl.find_pos(*args)
find_pos = _avl.find_pos

def counts(*args):
  return _avl.counts(*args)
counts = _avl.counts

def rot_l(*args):
  return _avl.rot_l(*args)
rot_l = _avl.rot_l

def rot_r(*args):
  return _avl.rot_r(*args)
rot_r = _avl.rot_r

def bf(*args):
  return _avl.bf(*args)
bf = _avl.bf

def tra(*args):
  return _avl.tra(*args)
tra = _avl.tra

def starts():
  return _avl.starts()
starts = _avl.starts

def del_min():
  return _avl.del_min()
del_min = _avl.del_min

def deletes(*args):
  return _avl.deletes(*args)
deletes = _avl.deletes

def prints():
  return _avl.prints()
prints = _avl.prints


